"Daryl S. Alas",
"Edcin E. Alcoser",
"Ronel S. Ampong "
"Aaron P. Atienza ",
"Ivan D. Benusa  ",
"Paul R. Beyong  ",
"Junny Boy L. Cabintoy",
"Darwin S. Castro ",
"Edwin N. Elmido ",
"Rexander B. Espina ",
"Mark L. Fuentes ",
"Vincent Rafael L. Laderas",
"Donald C. Larioque ",
"Mark Gary M. Mistula  ",
"Anghelo L. Olita ",
"Kelvin Jay R. Pernites",
"Rico Jay F. Porazo ",
"Weslie Vertudazo ",
"Ruffa Mae L. Aluyog ",
"Marian Nicol P. Lomonsod",
"Crystal S. Madrona ",
"M-Jay J. Mediona ",
"Malou U. Olazo  ",
"Ma. Cherry C. Perez",
"Ayheza Mae A. Regis ",
"Rochell C. Ritaga ",
"Janelle R. Rivera ",
"Althea Genesis S. Tarinque",
"Cyrine A. Tejero ",
"Jello G. Veros ",
"Gialyn A. Torotoro",
"Jeil C. Alvero ",
"Kent Joshua R. Belanigue",
"Jade B. Cabal ",
"King B. Cinco ",
"Mark Jade G. Cinco",
"Wesley Franz P. Cultura",
"John Paul L. Cumpio ",
"Nicole B. Balano ",
"Jenybe E. Bug-Atan ",
"Jessil E. Canuday ",
"Zyra D. Cuysona ",
"Allison Fate P. Dalugdugan",
"April Jean E. Delgado ",
"Jamilla Nicole R. Cabrera",
"Rouna Joy M. Golo ",
"Rainier D. De Paz ",
"Kevin G. Delgado ",
"Reymart A. Gabrera ",
"Gabriel Loreño ",
"John Rich R. Loreño",
"Justine J. Moquia ",
"Julius D. Olazo ",
"Christopher A. Porcadilla",
"Aldrin Jay A. Salmoro ",
"John Michael A. Samocino ",
"Louise Joy L. Almaden ",
"Rhea Mae D. Baristo ",
"Julian P. Cabal ",
"Crystal N. Cabia ",
"Jhoy A. Ceno ",
"Ivy G. Chavez ",
"Aira B. De Paz  ",
"Reiza Mae C. De Paz",
"Ma. Jenny A. Gabrera ",
"Madelyn E. Garcia ",
"Mariel A. Impuesto ",
"Nimfa V. Impuesto ",
"Meriam O. Kininahan ",
"Lovely Joy P. Lumbre ",
"Rhea Mae D. Mecairan ",
"Madonna C. Noveda ",
"Chamille D. Olarte ",
"Jilamae B. Pasadas ",
"Angelie D. Realino ",
"Princess Diane V. Ringor",
"Shiena Mae L. Ritaga ",
"Joyce M. Sabonsolin",
"Sabelle O. Tisado "


"Isagani C. Andales",
"Roziel Mae A. Barrio", 
"Jaymark R. Bansig ",
"Ronald L. Barcelon ",
"Ruben N. Barquin,",
"Junray Jr. Cantilang", 
"Edison Jr. R. Caspe", 
"Joshua P. Ceda", 
"Frances Mel T. Corayag", 
"Jessie M. Cuizon",
"Angelou S. Daniel",
"John Dave L. Delgado", 
"Kyle Shane Delgado", 
"James N. Diaz", 
"jude Mark Z. Diaz",  
"Rowel L. Diaz", 
"James F. Doblun", 
"Christian B. Dublas", 
"James Ashley M. Elmido", 
"Gino A. Escuadra", 
"Fate Gerald P. Gonzaga", 
"Kian Carlo Grospe", 
"Prince Ronald Labides", 
"Elgie L. Lacbayo", 
"Junnard Robert H. Liporada", 
"Ryan C. Naval", 
"Mark John P. Norega", 
"Nevada Dawn James Padero", 
"Stephen Jr. C. Robin", 
"R-Jay M. Ruanes",
"Ronron B. Rufil",
"Jumong P. Sarzuela", 
"Jason C. Terante",
"Jairus Kylle E. Tomines", 
"Rasel D. Villezas",
"John Rey D. Yayon"




"Jay P. Degrano",
"John Airon D. Gadon", 
"John Steven M. Tomines", 
"Adrian D. Gallos",
"Cassandra Julian T. Donayre", 
"Ricky Boy L. Sabili ",
"John Mark R. Lawag ",
"Mark Lorence R. Soria", 
"Junny Boy L. Cabintoy", 
"Paul R. Beyong", 
"Daryl S. Alas", 
"Malou U. Olazo", 
"Jumong P. Sarzuela", 
"Christian B. Dublas", 
"Nevada Dawn James Padero", 
"Roziel Mae A. Barrio", 
"Nimfa V. Impuesto",  
"Gabriel Loreño ",
"Shiena Mae L. Ritaga", 
"John Paul L. Cumpio ",
"Sara Claire A. Baquiro", 
"Francis D. Tan ",
"Jerald Jay U. Del Monte", 
"Stephany R. Gelarzo ",
"John Nikko A. Adaya ",
"Justine H. De Leon ",
"Joshua H. De Leon ",
"Alyssa Mae R. Lopez ",
"Princess Marie D. Navarro ",
"Arianne Mae V. Austero ",
"Lealyn M. Corbes ",
"John Ray C. Manlangit", 
"Prince Carl A. Paran ",
"Camille Abuana ",
"Angelika Q. Labares", 
"Jemuel A. Pallar "



"Princess Nazzariane A. Cabsag",
"Lance C. Cabilogan ",
"Jayson A. Obias ",
"Aira B. Delon ",
"Alyssa D. Elmido ",
"Hans Jespher A. Alfante ",
"Cheska R. Cecilio ",
"Angel L. Gabrera ",
"Lady Hone T. Macasocol",
"Erica Lein A. Austero ",
"Allysa Mae R. Lopez ",
"Jiel C. Alvero ",
"Joshua N. Alvero ",
"Cesario R. Barquin Jr. ",
"Albert G. Cruzada ",
"Lorence A. Malarejes ",
"Aeron V. Quitain ",
"Prince Carl A. Paran ",
"Angel Mae A. Galenzoga ",
"Ma Cristine T. Perjes ",
"Genos Denver A. Hinunangan"


"John Mark A. Lawag ",
"Jhon Kevin C. Boticalao ",
"Harold Alavera ",
"Ricky Boy L. Sabili ",
"Rogie C. Navarro ",
"Lorence A. Malarejes ",
"Aaron P. Atienza ",
"Zyra D. Cuysona ",
"Christal T. Loreño ",
"Marielle C. Bonife ",
"Julia Mae B. Gimena ",
"Ma. Cristine T. Perjes ",
"Gialyn A. Torotoro ",
"Jasmine A. Paler ",
"Angela C. Atienza ",
"Ivan D. Benusa ",
"Princess Nazzarianne A. Cabsag",
"John Steven M. Tomines ",
"Jemwel L. Aluyog  ",
"Frederick Jr. N. Gacita ",
"Niño Angelo C. Gilbuena ",
"Wilmar B. Lleve ",
"Nevada Dawn James Padero "

.my-div {
  position: relative;
  background: blue; /* main background color */
  padding: 50px;
  color: white;
  overflow: hidden; /* hide anything outside the div */
}

/* This will create the yellow corner */
.my-div::after {
  content: "";
  position: absolute;
  bottom: 0;
  right: 0;
  width: 10%;
  height: 10%;
  background: yellow;
}
